version: '3'
services:
  app:
    image: 815111324020.dkr.ecr.eu-central-1.amazonaws.com/stepanyan:v1.0.21
    ports:
      - 50000:50000
    environment:
      - TRAINER_NAME=Karen Kostanyan
      - PORT=50000