---
# defaults file for Exsamen
ubuntu_pkg: ["ca-certificates",  "curl", "gnupg", "unzip"]
amazon_pkg: ["yum-utils", "unzip"]
docker_pkg: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin"] 