---
# tasks file for Exsamen
#
- name: Install the correct web server for amazon linux
  import_tasks: amazon.yml
  when: ansible_facts['distribution']|lower == 'amazon'

- name: Install the correct web server for ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['distribution']|lower == 'ubuntu'

- name: Install the correct web server for ubuntu
  import_tasks: update_upgrade.yml
  when: ansible_facts['distribution']|lower == 'ubuntu'

- name: Download docker compose file
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "a+x"

- name: Check if aws cli exists
  ansible.builtin.shell: aws --version
  register: aws_out
  ignore_errors: true 