---
# tasks file for demo
#

- name: Get user information
  ansible.builtin.shell: cat /etc/passwd
  register: user_info

- name: Add the user 'bdg' with a specific uid and a primary group of 'sudo'
  ansible.builtin.user:
    name: bdg
    comment: my demo user
    uid: 1040
    group: sudo
    shell: /bin/bash
    password: "{{ 'admin' | password_hash('sha512', 'salt') }}"
  when: user_info.stdout.find('bdg') != -1

- name: Create .ssh directory
  ansible.builtin.file:
    path: /home/bdg/.ssh 
    state: directory
    owner: bdg
    group: sudo

- name: copy authorized_keys file
  ansible.builtin.copy:
    src: authorized_keys 
    dest: /home/bdg/.ssh/authorized_keys
    owner: bdg
    group: sudo
    mode: '0400' 

- name: Install the correct web server for amazon linux
  import_tasks: amazon.yml
  when: ansible_facts['distribution']|lower == 'amazon'

- name: Install the correct web server for ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['distribution']|lower == 'ubuntu'

- name: Check if aws cli exists
  ansible.builtin.shell: aws --version
  register: aws_out
  ignore_errors: true

- name: Download awccli zip file
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /home/bdg/awscliv2.zip
  when: aws_out.rc != 0

- name: Unarchive amazon cli zip 
  ansible.builtin.unarchive:
    src: /home/bdg/awscliv2.zip
    dest: /home/bdg
    remote_src: yes
  when: aws_out.rc != 0

- name: install aws cli
  ansible.builtin.shell: /home/bdg/aws/install
  when: aws_out.rc != 0
