name: Docker build image and push to ECR

on:
  push:
    tags:
      - 'v*' # Следующая строка проверяет семантическую версию
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Извлечение всей истории для получения доступа к тегам

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCSES_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region: eu-central-1

      - name: Get tag name
        id: get_tag
        run: echo ::set-output name=TAG_NAME::HTTP_server-${GITHUB_REF#refs/tags/}
  
      - name: Check tag format
        run: |
            if [[ ! "${{ steps.get_tag.outputs.TAG_NAME }}" =~ ^HTTP_server-v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Неверный формат тега. Разрешены только семантические версии тегов."
              exit 1
            fiHTTP_server
      - name: Log in to Amazon ECR
        run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 815111324020.dkr.ecr.eu-central-1.amazonaws.com/stepanyan

      - name: Build Docker image
        run: |
          docker build -t HTTP_server:${{ steps.get_tag.outputs.TAG_NAME }} -f Dockerfile .
        working-directory: ${{ github.workspace }}

      - name: Tag and push Docker image to AWS ECR
        run: |
          docker tag HTTP_server:${{ steps.get_tag.outputs.TAG_NAME }} 815111324020.dkr.ecr.eu-central-1.amazonaws.com/stepanyan:${{ steps.get_tag.outputs.TAG_NAME }}
          docker push 815111324020.dkr.ecr.eu-central-1.amazonaws.com/stepanyan:${{ steps.get_tag.outputs.TAG_NAME }}
          
      - name: Execute version and name
        run: |
          echo "Название приложения: HTTP_server"
          echo "Версия тега: ${{ steps.get_tag.outputs.TAG_NAME }}"