name: Docker build image and push to ECR
env:
  APPLICATION_NAME: "Flask"
  VERSION_TAG: "Flask-deploy-ver-${{ github.sha }}"

on:
  pull_request:
    paths:
      - 'app-code/**'
      - 'Dockerfile'
  push:
    branches:
      - 'main'
    paths:
      - 'app-code/**'
      - 'Dockerfile'    

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCSES_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region: eu-central-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 815111324020.dkr.ecr.eu-central-1.amazonaws.com/stepanyan

      - name: Build Docker image
        run: |
         docker build -t flask:${{ env.VERSION_TAG }} -f Dockerfile .
        working-directory: ${{ github.workspace }}



      - name: Tag and push Docker image to AWS ECR
        run: |
          docker tag flask:${{ env.VERSION_TAG }} 815111324020.dkr.ecr.eu-central-1.amazonaws.com/stepanyan:${{ env.VERSION_TAG }}
          docker push 815111324020.dkr.ecr.eu-central-1.amazonaws.com/stepanyan:${{ env.VERSION_TAG }}

      - name: Execute version and name
        run: |
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          echo "Version tag: ${{ env.VERSION_TAG }}"
